[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_plus = "2GwmwMwY8AgMtKcPG7CP7CBHtUcYV7ANqakTUtyuRVJL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
