[package]
name = "task_2_10"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.0.5"
dotenv = "0.15.0"
serde_json = "1.0.124"
solana-client = "2.0.5"
spl-token = "6.0.0"
spl-associated-token-account = "4.0.0"
bincode = "1.3.3"