[package]
name = "rust-ver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "2.0.5"
dotenv = "0.15.0"
serde_json = "1.0.124"
solana-client = "2.0.5"